# Generated by Django 4.0 on 2021-12-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0004_alter_lendedgames_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendedgames',
            name='time_period',
            field=models.IntegerField(),
        ),
    ]
